### ISSUE TITLE
my Minecraft 1.19 isn't working

### ISSUE THREAD

**Issue by svmf2022** [minecraft-linux/mcpelauncher-manifest#698]
22:32:49.226
launcher
main
Preparing to launch minecraft client for 1.19-forge-41.0.38
22:32:52.072
launcher
main
Checking installations.
22:32:52.075
launcher
main
Minecraft client 1.19-forge-41.0.38 is ready to start.
22:32:52.076
launcher
main
Starting!
22:32:52.077
launcher
main
Version does not support log configuration, will assume one plaintext entry per line
22:32:54.253
game
2022-06-19 22:32:54,249 main WARN Advanced terminal features are not available in this environment
22:32:54.401
game
[22:32:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, svmf2015, --version, 1.19-forge-41.0.38, --gameDir, /home/samuel/.minecraft, --assetsDir, /home/samuel/.minecraft/assets, --assetIndex, 1.19, --uuid, e2b5ddaa08ea4845b5433b1b2a972c8d, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 41.0.38, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129]
22:32:54.404
game
[22:32:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.1+10.0.1+main.e9521dc3 starting: java version 17.0.3.1 by Oracle Corporation; OS Linux arch amd64 version 5.4.0-52-generic
22:32:54.529
game
[22:32:54] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/samuel/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
22:32:54.787
game
[22:32:54] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/samuel/.minecraft/libraries/net/minecraftforge/fmlcore/1.19-41.0.38/fmlcore-1.19-41.0.38.jar is missing mods.toml file
22:32:54.789
game
[22:32:54] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/samuel/.minecraft/libraries/net/minecraftforge/javafmllanguage/1.19-41.0.38/javafmllanguage-1.19-41.0.38.jar is missing mods.toml file
22:32:54.791
game
[22:32:54] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/samuel/.minecraft/libraries/net/minecraftforge/lowcodelanguage/1.19-41.0.38/lowcodelanguage-1.19-41.0.38.jar is missing mods.toml file
22:32:54.793
game
[22:32:54] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/samuel/.minecraft/libraries/net/minecraftforge/mclanguage/1.19-41.0.38/mclanguage-1.19-41.0.38.jar is missing mods.toml file
22:32:54.862
game
[22:32:54] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
22:32:55.926
game
[22:32:55] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19-forge-41.0.38, --gameDir, /home/samuel/.minecraft, --assetsDir, /home/samuel/.minecraft/assets, --uuid, e2b5ddaa08ea4845b5433b1b2a972c8d, --username, svmf2015, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, msa, --versionType, release]
22:32:58.488
game
[22:32:58] [pool-3-thread-1/INFO] [minecraft/DataFixers]: Building optimized datafixer
22:33:00.652
game
[LWJGL] Failed to load a library. Possible solutions:
22:33:00.652
game
a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
22:33:00.652
game
b) Add the JAR that contains the shared library to the classpath.
22:33:00.652
game
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
22:33:00.652
game
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
22:33:01.004
game
Exception in thread "Render thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
22:33:01.004
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
22:33:01.005
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
22:33:01.005
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
22:33:01.005
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
22:33:01.005
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
22:33:01.005
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
22:33:01.005
game
at cpw.mods.bootstraplauncher@1.1.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155)
22:33:01.005
game
Caused by: java.lang.reflect.InvocationTargetException
22:33:01.005
game
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:33:01.005
game
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:33:01.005
game
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:33:01.005
game
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:33:01.005
game
at MC-BOOTSTRAP/fmlloader@1.19-41.0.38/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
22:33:01.005
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.1/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
22:33:01.005
game
... 7 more
22:33:01.006
game
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
22:33:01.006
game
at TRANSFORMER/minecraft@1.19/net.minecraft.SystemReport.m_143522_(SystemReport.java:65)
22:33:01.006
game
at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_167850_(Minecraft.java:2188)
22:33:01.006
game
at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_167872_(Minecraft.java:2181)
22:33:01.006
game
at TRANSFORMER/minecraft@1.19/net.minecraft.client.main.Main.main(Main.java:178)
22:33:01.006
game
... 13 more
22:33:01.440
monitor
Process Monitor
Process crashed with exit code 1

**Comment by svmf2022** [comment]
can someone help me please?

**Comment by Muvkina** [comment]
1.19 isn't supported yet, try to be patient

**Comment by ChristopherHX** [comment]
Wrong game, this is for Java Edition. However this launcher is for the Android Version
